WebShop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('', include('watches.urls')),
    path('accounts/', include('django.contrib.auth.urls')), 
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.urls import reverse_lazy

from .views import RegistrationFormView, logout, Profile ,ChangeProfile
from django.contrib.auth.views import ( LoginView, LogoutView, PasswordChangeDoneView,PasswordChangeView,
                        PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, 
                        PasswordResetCompleteView )


app_name = 'user'

urlpatterns = [
     path('login', LoginView.as_view(template_name='registration/login.html'), name='login'),
     path('logout',LogoutView.as_view(next_page='/') , name='logout'),

    path('password-change', PasswordChangeView.as_view(
        template_name='registration/password_change_form.html', success_url = 'password-change/done'), name='password-change'),
    path('password-change/done', PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),
         name='password-change-done'),




    path('register', RegistrationFormView.as_view(), name='register'),
    path('profile', Profile, name='profile'),
    path('changeuser',ChangeProfile,name='change')

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document=settings.STATIC_ROOT)

watches/urls.py
from django.urls import path
from .views import ( ProductDetail, HomeView,  add_to_cart, 
            remove_from_cart, remove_single_item_from_cart, OrderSummaryView, index,
            AddCouponView,
            CheckoutView,
            PaymentView,
            SearchResultsView,
            )
app_name = 'watch'
urlpatterns = [
    path('index/',index, name='index'),
    path('watch/<slug>', ProductDetail.as_view(), name='product'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('', HomeView.as_view(), name='home'),
    path('payment/<payment_option>/', PaymentView.as_view(),name='payment'),
    path('search/', SearchResultsView.as_view(), name='search_results'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart, name='remove-single-item-from-cart'),
]   

user/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
import stripe
from django.db.models.signals import post_save

# Create your models here.
stripe.api_key = settings.STRIPE_SECRET_KEY


class userProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    phone = models.CharField(max_length=10, blank=True, null=True)
    image = models.ImageField(upload_to='Avatar', blank=True, null=True)
    # description = models.TextField(default='description default text ')

    def __str__(self):
        return self.user.username

class userStripe(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    stripe_id = models.CharField(max_length=120, null=True, blank=True)

    def __str__(self):
        if self.stripe_id:
            return self.stripe_id
        else:
            return self.user.username

def stripeCallBack(sender, instance, created, *args, **kwargs):
    user_stripe_account, created = userStripe.objects.get_or_create(
        user=instance)
    if created:
        print('Create for {}'.format(instance.username))
    if user_stripe_account.stripe_id is None or user_stripe_account.stripe_id == '':
        new_stripe_id = stripe.Customer.create(email=instance.email)
        user_stripe_account.stripe_id = new_stripe_id['id']
        user_stripe_account.save()

def userprofile_receiver(sender, instance, created, *args, **kwargs):
    if created:
        userprofile = userProfile.objects.create(user=instance)

post_save.connect(userprofile_receiver, sender=settings.AUTH_USER_MODEL)

post_save.connect(stripeCallBack, sender=settings.AUTH_USER_MODEL)

watches/models.py
from django.db.models.signals import post_save
from django_countries.fields import CountryField
from django.shortcuts import reverse
from django.conf import settings
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.template.defaultfilters import slugify
from django.shortcuts import reverse
from django.db.models.signals import post_save
from image_cropping import ImageRatioField
from ckeditor.fields import RichTextField
# Create your models here.

ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shopping'),
)

PAYMENT_CHOICES = (
    ('C', 'Cash On Delivery'),
    ('P', 'PayPal')
)

class Categorize(models.Model):
    name = models.CharField(max_length=100)
    date_create = models.DateTimeField(auto_created=True, auto_now_add=True)
    date_update = models.DateTimeField(auto_now_add=True, auto_created=True)
    descriptions = models.CharField(max_length=250, blank=True)

    def __str__(self):
        return self.name


class Specification(models.Model):
    detail = models.CharField(max_length=255,blank=True, null=True)

    def __str__(self):
        return self.detail


class HighLight(models.Model):
    highlight = models.CharField(max_length=225)
    detail = models.CharField(max_length=150, blank=True, null=True)

    def __str__(self):
        return self.highlight

class Specifications(models.Model):
    name = models.CharField(max_length=50, blank=True, null= True)
    specifications = models.ManyToManyField(Specification, blank=True)

    def __str__(self):
        return self.name


class Watches(models.Model):
    name = models.CharField(max_length=25)
    brand = models.CharField(max_length=255, blank=True, null=True)
    categorize = models.ForeignKey(Categorize, on_delete=models.CASCADE, blank=True, null=True)
    # price_before_discount = models.DecimalField(max_digits=6, decimal_places=2)
    price_before_discount = models.FloatField(blank=True, null=True)

    image = models.ImageField(upload_to='Image', blank=True, null=True)
    specifications = models.ForeignKey('Specifications', on_delete=models.SET_NULL, blank=True, null=True)
    description = RichTextField(blank=True, null=True)
    intro = models.CharField(max_length=255, blank=True, null=True)
    highlight = models.ManyToManyField('HighLight', blank=True)
    discount = models.IntegerField(default=0, blank=True)
    price = models.FloatField(blank=True, null=True)
    slug = models.SlugField(blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def set_intro(self):
        self.intro =self.description.split('.')[0]
        return self.intro

    def __str__(self):
        return self.name

    def set_price(self):
        self.price = self.price_before_discount - self.price_before_discount * self.discount/100
        return self.price

    def get_absolute_url(self):
        return reverse("watch:product", kwargs={
            'slug': self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("watch:add-to-cart", kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("watch:remove-from-cart", kwargs={
            'slug': self.slug
        })

    


    def save(self, *args, **kwargs):
        self.intro = self.set_intro()
        self.price = self.set_price()
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE, blank=True, null=True)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Watches, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.name}"

    def get_total_item_price(self):
        return self.quantity * self.item.price_before_discount

    def get_total_discount_item_price(self):
        return self.quantity * self.item.price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount > 0 :
            return self.get_total_discount_item_price()
        else:
            return self.get_total_item_price()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    option_pay = models.CharField(max_length=1,choices=PAYMENT_CHOICES,blank=True, null=True)
    ref_code = models.CharField(max_length=20, blank=True, null=True)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateField(auto_now_add=True)
    ordered = models.BooleanField(default=False)
    billing_address = models.ForeignKey('Address', related_name='billing_address', on_delete=models.SET_NULL,
                                        blank=True, null=True)
    shipping_address = models.ForeignKey('Address', related_name='shipping_address', on_delete=models.SET_NULL,
                                         blank=True, null=True)
    payment = models.ForeignKey(
        'Payment', on_delete=models.SET_NULL, blank=True, null=True)
    coupon = models.ForeignKey(
        "Coupon", on_delete=models.SET_NULL, blank=True, null=True)
    being_delivered = models.BooleanField(default=False)
    price = models.FloatField(null=True)
    received = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username
    
    def get_total_price(self):
        total= 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        return total

    def get_total_price_with_coupon(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        if self.coupon:
            total -= self.coupon.amount
        self.price = total
        return total, self.price


class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    # first_name = models.CharField(max_length=255,blank=True,null=True)
    # last_name = models.CharField(max_length=255,blank=True,null=True)
    # phone = models.CharField(max_length=15,blank=True,null=True)
    # phone = models.EmailField(max_length=100,blank=True,null=True)
    company = models.CharField(max_length=255, blank=True, null=True)             
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    # city = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = "Addresses"


class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    amount = models.FloatField(blank=True, null=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


class Coupon(models.Model):
    code = models.CharField(max_length=15, blank=True, null=True)
    amount = models.FloatField()

    def __str__(self):
        return self.code


class Refund(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    reason = models.TextField()
    accepted = models.BooleanField(default=False)
    email = models.EmailField()

    def __str__(self):
        return f"{self.pk}"

templates/base.html
{% load static %}
<html class="no-js" lang="zxx">


<!-- Mirrored from demo.devitems.com/mirora-v2/mirora/product-details.html by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 21 May 2019 06:15:30 GMT -->

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="meta description">
    <!-- Favicons -->
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">
    <link rel="apple-touch-icon" href="{% static 'img/icon.png' %}">

    <!-- Title -->
    <title>Mirora - Watch & Luxury Store Bootstrap 4 Template</title>

    <!-- ************************* CSS Files ************************* -->

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <!-- Font Awesome CSS -->
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">

    <!-- Elegent Icon CSS -->
    <link rel="stylesheet" href="{% static 'css/elegent-icons.css' %}">

    <!-- All Plugins CSS css -->
    <link rel="stylesheet" href="{% static 'css/plugins.css' %}">

    <!-- style css -->
    <link rel="stylesheet" href="{% static 'css/main.css' %}">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">

    <!-- modernizr JS
    ============================================ -->
    <script src="{% static 'js/vendor/modernizr-2.8.3.min.js' %}"> </script>
    <script src="http://casiocdn.com/casio-v2/resource/theme/scripts/modernizr-2.8.3.js"></script>
    {% block css %}

    {% endblock %}
    <!--[if lt IE 9]>
    <script src="//oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js' %}"></script>
    <script src="//oss.maxcdn.com/respond/1.4.2/respond.min.js' %}"></script>
    <![endif]-->

</head>

<body>
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert" style="margin-bottom: 0rem;">
        <strong>{{ message }}</strong>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endfor %}
    {% endif %}
    <div class="wrapper bg--shaft">
        {% include "header.html" %}
        {% block content%}
        {% endblock %}
        {% include "footer.html" %}
        <!-- Scroll To Top Start -->
        <a class="scroll-to-top" href="#"><i class="fa fa-angle-double-up"></i></a>
        <!-- Scroll To Top End -->
    </div>
    <!-- jQuery JS -->
    <script src="{% static 'js/vendor/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/plugins.js' %}"></script>
    <script src="{% static 'js/ajax-mail.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>

    {% block script %}

    {% endblock %}
</body>

</html>

templates/header.html
{% load static %}
{% load cart_template_tags %}
<header class="header headery-style-1">
    <div class="header-top header-top-1">
        <div class="container">
            <div class="row no-gutters align-items-center">
                <div class="col-lg-8 d-flex align-items-center flex-column flex-lg-row">
                    <!-- <ul class="social social-round mr--20">
                        <li class="social__item">
                            <a href="twitter.com" class="social__link">
                                <i class="fa fa-twitter"></i>
                            </a>
                        </li>
                        <li class="social__item">
                            <a href="plus.google.com" class="social__link">
                                <i class="fa fa-google-plus"></i>
                            </a>
                        </li>
                        <li class="social__item">
                            <a href="facebook.com" class="social__link">
                                <i class="fa fa-facebook"></i>
                            </a>
                        </li>
                        <li class="social__item">
                            <a href="youtube.com" class="social__link">
                                <i class="fa fa-youtube"></i>
                            </a>
                        </li>
                        <li class="social__item">
                            <a href="instagram.com" class="social__link">
                                <i class="fa fa-instagram"></i>
                            </a>
                        </li>
                    </ul> -->
                    <p class="header-text">Free shipping on all domestic orders with coupon code
                        <span>“Watches2018”</span></p>
                </div>
                <div class="col-lg-4">
                    <div class="header-top-nav d-flex justify-content-lg-end justify-content-center">
                        <div class="language-selector header-top-nav__item">
                            <div class="dropdown header-top__dropdown">
                                <a class="dropdown-toggle" id="languageID" data-toggle="dropdown" aria-haspopup="true"
                                    aria-expanded="false">
                                    EN-GB
                                    <i class="fa fa-angle-down"></i>
                                </a>
                                <div class="dropdown-menu" aria-labelledby="languageID">
                                    <a class="dropdown-item" href="#"><img src="{% static 'img/header/1.jpg' %}"
                                            alt="English"> English</a>
                                    <a class="dropdown-item" href="#"><img src="{% static 'img/header/2.jpg' %}"
                                            alt="Français"> Français</a>
                                </div>
                            </div>
                        </div>
                        <div class="currency-selector header-top-nav__item">
                            <div class="dropdown header-top__dropdown">

                                <a class="dropdown-toggle" id="currencyID" data-toggle="dropdown" aria-haspopup="true"
                                    aria-expanded="false">
                                    USD
                                    <i class="fa fa-angle-down"></i>
                                </a>
                                <div class="dropdown-menu" aria-labelledby="currencyID">
                                    <a class="dropdown-item" href="#">&euro; Uro</a>
                                    <a class="dropdown-item" href="#">&pound; Pound Sterling</a>
                                    <a class="dropdown-item" href="#">&dollar; Us Dollar</a>
                                </div>
                            </div>
                        </div>
                        <div class="user-info header-top-nav__item">
                            <div class="dropdown header-top__dropdown">
                                {% if user.is_authenticated %}
                                <a class="dropdown-toggle" id="userID" data-toggle="dropdown" aria-haspopup="true"
                                    aria-expanded="false">
                                    {{ request.user }}
                                    <i class="fa fa-angle-down"></i>    
                                </a>
                                <div class="dropdown-menu" aria-labelledby="userID">
                                    <a class="dropdown-item" href="{% url 'user:profile' %}">Profile</a>
                                    <a class="dropdown-item" href="{% url 'user:logout' %}">Log out</a>
                                </div>
                                {% else %}
                                <a class="dropdown-toggle" id="userID" data-toggle="dropdown" aria-haspopup="true"
                                    aria-expanded="false">
                                    My Account
                                    <i class="fa fa-angle-down"></i>
                                </a>
                                <div class="dropdown-menu" aria-labelledby="userID">
                                    <a class="dropdown-item" href="{% url 'user:register' %}">Register</a>
                                    <a class="dropdown-item" href="{% url 'user:login' %}">Log In</a>
                                </div>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="header-middle header-top-1">
        <div class="container">
            <div class="row no-gutters align-items-center">
                <div class="col-md-5 col-sm-6 order-lg-1 order-2">
                    <div class="contact-info">
                        <img src="{% static 'img/icons/icon_phone.png' %}" alt="Phone Icon">
                        <p>Call us <br> Free Support: (012) 800 456 789</p>
                    </div>
                </div>
                <div class="col-lg-2 col-12 order-lg-2 order-1 text-center">
                    <a href="{% url 'watch:home' %}" class="logo-box mb-md--30">
                        <img src="{% static 'img/logo/logo.png' %}" alt="logo">
                    </a>
                </div>
                <div class="col-lg-5 col-md-7 col-sm-6 order-lg-3 order-3">
                    <div class="header-toolbar">
                        <div class="search-form-wrapper search-hide">
                            <form action="{% url 'watch:search_results' %}" class="search-form" method="GET">
                                <input type="text" name="q" id="search" class="search-form__input"
                                    placeholder="Search entire store here..">
                                <button type="submit" class="search-form__submit">
                                    <i class="icon_search"></i>
                                </button>
                            </form>
                        </div>
                       
                        <ul class="header-toolbar-icons">
                            <li class="search-box">
                                <a href="#" class="bordered-icon search-btn" aria-expanded="false"><i
                                        class="icon_search"></i></a>
                            </li>
                            <li class="mini-cart-icon">
                                <div class="mini-cart mini-cart--1">
                                   
                                    <a href="{% url 'watch:order-summary' %}"
                                        class="mini-cart__dropdown-toggle bordered-icon">
                                        {% if request.user.is_authenticated and request.user|cart_item_count > 0%}
                                        <span class="mini-cart__count">{{ request.user|cart_item_count }}</span>
                                        {% endif %}
                                        <i class="icon_cart_alt mini-cart__icon"></i>
                                        <!-- <span class="mini-cart__ammount"> <i class="fa fa-angle-down"></i></span> -->
                                    </a>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Eidt</h1>
    <form action="" method="post">
        <h1>trung</h1>
       <form action="" method="post">
           {% csrf_token %}
           {{ form_user.as_p }}
           {{ form.as_p }}
       </form>
    </form>
</body>
</html>

templates/my-account.html
{% extends 'base.html' %}
{% block content %}
<!-- Breadcumb area Start -->
<div class="breadcrumb-area">
    <div class="container">
        <div class="row">
            <div class="col-12 text-center">
                <h1 class="page-title">My Account</h1>
                <ul class="breadcrumb justify-content-center">
                    <li><a href="index.html">Home</a></li>
                    <li class="current"><a href="{% url 'user:profile' %}">My Account</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>
<!-- Breadcumb area End -->

<!-- Main Content wrapper start -->

<section class="main-content-wrapper">
    <div class="account-wrapper pt--40 pb--80 pt-md--30 pb-md--60">
        <div class="container">
            <div class="user-dashboard-tab">
                <div class="row">
                    <div class="col-lg-4 mb-md--30">
                        <div class="user-dashboard-tab__head nav flex-column" role="tablist"
                            aria-orientation="vertical">
                            <a class="nav-link "  role="tab" href="{% url 'user:profile' %}"
                                aria-controls="dashboard" aria-selected="true">Dashboard</a>

                            <a class="nav-link"  role="tab" href="{% url 'user:change' %}"
                                aria-controls="accountdetails" aria-selected="true">Account Details</a>
                            <a class="nav-link" href="{% url 'user:logout' %}">Logout</a>
                        </div>
                    </div>
                    <div class="col-lg-8">
                        <div class="user-dashboard-tab__content tab-content">
                            
                            <!-- <div class="tab-pane fade" id="accountdetails">
                                <div class="account-form bg--2">
                                    <form action="#" class="form">
                                        {% csrf_token %}
                                        <div class="form-row mb--20">
                                            <div class="col-12">
                                                <div class="form__group">
                                                    <label for="user_email" class="form__label">Username</label>
                                                    {{form_user.username.value}}
                                                    <input type="text" name="username" id="id_username"
                                                        class="form__input form__input--2"
                                                        value="{{form_user.username.value}}">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-row mb--20">
                                            <div class="col-md-6 mb-sm--20">
                                                <div class="form__group">
                                                    <label for="account_fname" class="form__label">First Name</label>
                                                    <input type="text" name="first_name" id="id_first_name"
                                                        value="{{form_user.first_name.value}}"
                                                        class="form__input form__input--2">
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form__group">
                                                    <label for="account_lname" class="form__label">Last Name</label>
                                                    <input type="text" name="last_name" id="id_last_name"
                                                        value="{{form_user.first_name.value}}"
                                                        class="form__input form__input--2">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-row mb--20">
                                            <div class="col-12">
                                                <div class="form__group">
                                                    <label for="user_email" class="form__label">Email Address</label>
                                                    <input type="email" name="email" id="id_email"
                                                        value="{{form_user.email.value}}"
                                                        class="form__input form__input--2">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-row mb--20">
                                            <div class="col-12">
                                                <div class="form__group">
                                                    <label for="user_email" class="form__label">Phone</label>
                                                    <input type="text" name="phone" id="id_phone"
                                                        value="{{form.phone.value}}" class="form__input form__input--2">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-row">
                                            <div class="col-12">
                                                <button type="submit" class="btn btn-medium btn-style-2">Save
                                                    Changes</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                                
                            </div> -->
                            {% block form %}
                            <div class="tab-pane fade show active" id="dashboard">
                                <p>Hello <strong>John</strong></p>
                                <p>From your account dashboard. you can easily <a
                                        href="{% url 'user:password-change' %}">edit your password</a>.</p>
                            </div>
                            {% endblock %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}